// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package entity

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC47cad3bDecodeGithubComRasikrrMyProjectInternalDomainEntity(in *jlexer.Lexer, out *MCQQuestion) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "question_id":
			out.QuestionID = string(in.String())
		case "question":
			out.Question = string(in.String())
		case "answer_options":
			out.AnswerOptions = string(in.String())
		case "image_question":
			out.ImageQuestion = bool(in.Bool())
		case "image_bytes":
			if in.IsNull() {
				in.Skip()
				out.ImageBytes = nil
			} else {
				out.ImageBytes = in.Bytes()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC47cad3bEncodeGithubComRasikrrMyProjectInternalDomainEntity(out *jwriter.Writer, in MCQQuestion) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"question_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.QuestionID))
	}
	{
		const prefix string = ",\"question\":"
		out.RawString(prefix)
		out.String(string(in.Question))
	}
	{
		const prefix string = ",\"answer_options\":"
		out.RawString(prefix)
		out.String(string(in.AnswerOptions))
	}
	{
		const prefix string = ",\"image_question\":"
		out.RawString(prefix)
		out.Bool(bool(in.ImageQuestion))
	}
	{
		const prefix string = ",\"image_bytes\":"
		out.RawString(prefix)
		out.Base64Bytes(in.ImageBytes)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MCQQuestion) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC47cad3bEncodeGithubComRasikrrMyProjectInternalDomainEntity(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MCQQuestion) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC47cad3bEncodeGithubComRasikrrMyProjectInternalDomainEntity(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MCQQuestion) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC47cad3bDecodeGithubComRasikrrMyProjectInternalDomainEntity(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MCQQuestion) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC47cad3bDecodeGithubComRasikrrMyProjectInternalDomainEntity(l, v)
}
func easyjsonC47cad3bDecodeGithubComRasikrrMyProjectInternalDomainEntity1(in *jlexer.Lexer, out *MCQAnswer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "question_id":
			out.QuestionID = string(in.String())
		case "answer":
			out.Answer = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC47cad3bEncodeGithubComRasikrrMyProjectInternalDomainEntity1(out *jwriter.Writer, in MCQAnswer) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"question_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.QuestionID))
	}
	{
		const prefix string = ",\"answer\":"
		out.RawString(prefix)
		out.String(string(in.Answer))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MCQAnswer) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC47cad3bEncodeGithubComRasikrrMyProjectInternalDomainEntity1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MCQAnswer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC47cad3bEncodeGithubComRasikrrMyProjectInternalDomainEntity1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MCQAnswer) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC47cad3bDecodeGithubComRasikrrMyProjectInternalDomainEntity1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MCQAnswer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC47cad3bDecodeGithubComRasikrrMyProjectInternalDomainEntity1(l, v)
}
