// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package mcq_test

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD2b7633eDecodeGithubComRasikrrMyProjectInternalPortsHttpHandlersMcqTest(in *jlexer.Lexer, out *mcqQuestion) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "question_id":
			out.QuestionID = string(in.String())
		case "question_text":
			out.QuestionText = string(in.String())
		case "answer_options":
			out.AnswerOptions = string(in.String())
		case "image_question":
			out.ImageQuestion = bool(in.Bool())
		case "image_bytes":
			if in.IsNull() {
				in.Skip()
				out.ImageBytes = nil
			} else {
				out.ImageBytes = in.Bytes()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrMyProjectInternalPortsHttpHandlersMcqTest(out *jwriter.Writer, in mcqQuestion) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"question_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.QuestionID))
	}
	{
		const prefix string = ",\"question_text\":"
		out.RawString(prefix)
		out.String(string(in.QuestionText))
	}
	{
		const prefix string = ",\"answer_options\":"
		out.RawString(prefix)
		out.String(string(in.AnswerOptions))
	}
	{
		const prefix string = ",\"image_question\":"
		out.RawString(prefix)
		out.Bool(bool(in.ImageQuestion))
	}
	{
		const prefix string = ",\"image_bytes\":"
		out.RawString(prefix)
		out.Base64Bytes(in.ImageBytes)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v mcqQuestion) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrMyProjectInternalPortsHttpHandlersMcqTest(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v mcqQuestion) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrMyProjectInternalPortsHttpHandlersMcqTest(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *mcqQuestion) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrMyProjectInternalPortsHttpHandlersMcqTest(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *mcqQuestion) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrMyProjectInternalPortsHttpHandlersMcqTest(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrMyProjectInternalPortsHttpHandlersMcqTest1(in *jlexer.Lexer, out *getMCQAnswersRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "questions":
			if in.IsNull() {
				in.Skip()
				out.Questions = nil
			} else {
				in.Delim('[')
				if out.Questions == nil {
					if !in.IsDelim(']') {
						out.Questions = make([]mcqQuestion, 0, 0)
					} else {
						out.Questions = []mcqQuestion{}
					}
				} else {
					out.Questions = (out.Questions)[:0]
				}
				for !in.IsDelim(']') {
					var v4 mcqQuestion
					(v4).UnmarshalEasyJSON(in)
					out.Questions = append(out.Questions, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrMyProjectInternalPortsHttpHandlersMcqTest1(out *jwriter.Writer, in getMCQAnswersRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"questions\":"
		out.RawString(prefix[1:])
		if in.Questions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Questions {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getMCQAnswersRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrMyProjectInternalPortsHttpHandlersMcqTest1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getMCQAnswersRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrMyProjectInternalPortsHttpHandlersMcqTest1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getMCQAnswersRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrMyProjectInternalPortsHttpHandlersMcqTest1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getMCQAnswersRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrMyProjectInternalPortsHttpHandlersMcqTest1(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrMyProjectInternalPortsHttpHandlersMcqTest2(in *jlexer.Lexer, out *answer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "question_id":
			out.QuestionID = string(in.String())
		case "answer":
			out.Answer = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrMyProjectInternalPortsHttpHandlersMcqTest2(out *jwriter.Writer, in answer) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"question_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.QuestionID))
	}
	{
		const prefix string = ",\"answer\":"
		out.RawString(prefix)
		out.String(string(in.Answer))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v answer) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrMyProjectInternalPortsHttpHandlersMcqTest2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v answer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrMyProjectInternalPortsHttpHandlersMcqTest2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *answer) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrMyProjectInternalPortsHttpHandlersMcqTest2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *answer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrMyProjectInternalPortsHttpHandlersMcqTest2(l, v)
}
